/* 	
	GOKZ Pistol Include File
	
	Website: https://bitbucket.org/kztimerglobalteam/gokz
*/

#if defined _gokz_pistol_included_
#endinput
#endif
#define _gokz_pistol_included_



// =========================  DEFINITIONS  ========================= //

#define PISTOL_OPTION_NAME "pistol"
#define PISTOL_OPTION_DESCRIPTION "Pistol"



// =========================  ENUMERATIONS  ========================= //

enum
{
	Pistol_USP = 0, 
	Pistol_Glock, 
	Pistol_P250, 
	Pistol_Dualies, 
	Pistol_Deagle, 
	Pistol_CZ75A, 
	Pistol_FiveSeveN, 
	Pistol_Tec9, 
	Pistol_R8Revolver, 
	Pistol_Disabled, 
	PISTOL_COUNT
}; 