/* 	
	GOKZ Tips Include File
	
	Website: https://bitbucket.org/kztimerglobalteam/gokz
*/

#if defined _gokz_tips_included_
#endinput
#endif
#define _gokz_tips_included_



// =========================  DEFINITIONS  ========================= //

#define TIPS_OPTION_NAME "tips"
#define TIPS_OPTION_DESCRIPTION "Tips"



// =========================  ENUMERATIONS  ========================= //

enum
{
	Tips_Disabled = 0, 
	Tips_Enabled, 
	TIPS_COUNT
}; 